### ISSUE TITLE
Replace SQLite with production-grade database

### ISSUE THREAD

**Issue by MitchellHarrison** [MitchellHarrison/stream-environment#2]
Check the following (suggestions recommended):
- [ ] MariaDB
- [ ] PostgreSQL
- [x] MySQL
- [x] Elasticsearch
- [x] CockroachDB

**Comment by absenth** [comment]
You might consider reading about both [mariadb](https://mariadb.org/) and [postgresql](https://www.postgresql.org/)

**Comment by MitchellHarrison** [comment]
Throwing out MySQL in lieu of MariaDB.

**Comment by VinylVault** [comment]
Postgres is more resilient than MariaDB - i'd recommend thouggh making it user chosen in a setup script

**Comment by matthewbrandt** [comment]
+1 postgres

**Comment by matthewbrandt** [comment]
cockroachDB is apparently very solid too

**Comment by MitchellHarrison** [comment]
Someone in chat during today's stream mentioned ElasticSearch. And while it looks really great for what it's designed for, I don't think it fits the project or my immediate goals.  
* It's very fast at a scale that I'll never need it to work at with this project. I could stream for years and not have the kind of data that it's built for. 
* I don't think I will be doing a ton of searching. Aggregating, yes. But not so many _searches_.
* With the size of my data, a good ol' RDBMS will probably be the best bet.  
* Implementation with ElasticSearch would probably be slower since I've only ever used SQLite and my brain is in RDMB mode. This doesn't feel like the time to change that.
  
Thanks for the current suggestions. Digging in on others now!

**Comment by MitchellHarrison** [comment]
CockroachDB is also interesting and a really cool solution for a lot of problems that this project isn't bringing. All of the automatic failover and scaling features are sweet, but this whole thing is going to be sitting in my office. It's a personal project, and I don't think it's worth giving up the insane amount of online help and community support that MariaDB or Postgres offers. So Cockroach, while awesome for what it does, is out.  
  
The last two (so far) to look at are Maria and Postgres! Your thoughts are welcome as ever.

**Comment by MitchellHarrison** [comment]
The PostgreSQL/MariaDB has been a hard one. I see the advantages of both, speaking from zero experience but a fair amount of research. It seems like Maria is a little lighter, which is great (although apparently there can be log file bloat at scale), but Postgres seems to handle NULL values and other [datatype issues](https://www.cybertec-postgresql.com/en/why-favor-postgresql-over-mariadb-mysql/) more strictly (which I view as a positive).  
  
But it also seems like Postgres, while better at scale, may be more complex than is strictly necessary for my little project. Honestly, SQLite would work, but I'm trying to avoid it anywhere beyond testing since part of the point of this project is to teach myself a proper production-grade database.  
  
I see some love for Postgres here, any Maria fans? Bear in mind the scope of my project, which is quite small comparatively. On another note, I prefer the documentation for Maria, but both are fine.

**Comment by MitchellHarrison** [comment]
After being tired of myself being so indecisive, I've decided that the dart on this issue has landed with Postgres. I like how much community support there is, it will work great for my this project, and it gives me an excuse to start playing with psychopg2 and sqlalchemy. I'm glad the decision is made, because it was causing me undue stress having something just sitting here waiting on a coin toss.

Can't wait to get started!
